# Site
title:              موقع ملهم
bio:                'دروس وشروحات قيّمة وحصريّة لا سابق لها في المحتوى العربي'
description:        "شغف المعرفة"
reading_time:       true
words_per_minute:   200
logo:               'assets/img/logo1.svg'
locale:             ar_SY
url:                https://mulham.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown      
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true


# Comments
disqus_shortname:  

# Social
# if you don't have any of social below, comment the line.
google:		          
  analytics:	UA-80564042-1
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:			mulham94@gmail.com
twitter:            mulham_ib
#facebook:           username
github:             mulham
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
youtube:          mulham94
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
# Gems
excerpt_separator: <!--more-->
plugins:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate
  - jekyll-archives

paginate: 12
paginate_path: /page:num/

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
